services:
  db:
    container_name: mysql_8
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "mudar123"
      MYSQL_DATABASE: "unicesumar"
    ports:
      - "3306:3306"
    volumes:
      - ./datadir:/var/lib/mysql
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    container_name: blog_cesumar
    image: node:18.20.4
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    links:
      - db
    depends_on:
      - db
    command: npm start
    working_dir: /app/
    restart: unless-stopped