services:
  db:
    container_name: mysql_8
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "mudar123"
      MYSQL_DATABASE: "unicesumar"
    ports:
      - "3306:3306"
    volumes:
      - ./datadir:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    image: node:18.20.4
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: mudar123
      MYSQL_DATABASE: unicesumar
    restart: unless-stopped